# Generated by Django 5.2.7 on 2025-10-29 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('data', models.DateField(help_text='Data da feira (yyyy-mm-dd)')),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fazenda', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.feira')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.produtor')),
            ],
        ),
    ]
